[project]
name = "ai-learning-notes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "torch>=2.9.1",
    "torchvision>=0.24.1",
]
